#!/bin/bash

#$1 - директория, которую необходимо проверить
#$2 - расширение файлов, которые необходимо удалить, например .gif

if [ -d $1 ]
then
	cd $1;
	rm $(ls *$2)
	echo 'done!'
else
	echo 'No such dir'
	exit 1
fi
