version: '3.9'
services:

  db:
    image: mariadb:10.10.2
    environment:
      MYSQL_ROOT_PASSWORD: hg
    volumes:
      - /home/db:/var/lib/mysql
    deploy:
      mode: global

  adminer:
    image: adminer:4.8.1
    depends_on:
      - db
    ports:
      - 6080:8080
    deploy:
      mode: global
